/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructuras.LQueue;
import Estructuras.Ventanillas;
import Estructuras.LinkedList;

public class ConfiguracionInicial extends javax.swing.JFrame {
   //Configuración
    Ventanillas Ventanas;
    LQueue ListaColaPerecederos;
    LQueue ListaColaNoPerecederos;

    /**
     * Creates new form ConfiguracionInicial
     */
    public ConfiguracionInicial() {
       
        initComponents();
        //Creamos los objetos de tipo cola.
        ListaColaPerecederos = new LQueue();
        ListaColaNoPerecederos = new LQueue();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NoPerecederosTag = new javax.swing.JLabel();
        PerecederosTag = new javax.swing.JLabel();
        CantVentPerecederos = new javax.swing.JComboBox<>();
        CantVentNoPerecederos = new javax.swing.JComboBox<>();
        QuioscoBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad de ventanillas por tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        NoPerecederosTag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoPerecederosTag.setText("Ventanillas no perecederos");
        getContentPane().add(NoPerecederosTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        PerecederosTag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PerecederosTag.setText("Ventanillas perecederos");
        getContentPane().add(PerecederosTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 20));

        CantVentPerecederos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "1 Ventana", "2 Ventanas", "3 ventanas", "4 ventanas", "5 Ventanas", " " }));
        CantVentPerecederos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CantVentPerecederosMouseClicked(evt);
            }
        });
        getContentPane().add(CantVentPerecederos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        CantVentNoPerecederos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "1 Ventana", "2 Ventanas", "3 ventanas", "4 ventanas", "5 Ventanas", " " }));
        getContentPane().add(CantVentNoPerecederos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));

        QuioscoBtn.setText("Quiosco");
        QuioscoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuioscoBtnMouseClicked(evt);
            }
        });
        getContentPane().add(QuioscoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, 80));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantVentPerecederosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CantVentPerecederosMouseClicked
  
    }//GEN-LAST:event_CantVentPerecederosMouseClicked

    private void QuioscoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuioscoBtnMouseClicked
        //Obtiene el valor seleccionado por el usuario de cantidad de ventanillas de no perecederos
        int SeleccionCantNoPere = CantVentNoPerecederos.getSelectedIndex();
        int num = 0;
       
        //Ingresa la cantidad de ventanillas seleccionadas de no perecederos
        if(SeleccionCantNoPere!=0){
            while(SeleccionCantNoPere!=0){
                String Nombre = "Ventana "+ num;
                Ventanillas Nueva = new Ventanillas(Nombre);
                ListaColaNoPerecederos.enqueue(Nueva);
                SeleccionCantNoPere--;
                num= num+1;
            }
        }
        else{
           
        }
  
        //Obtiene el valor seleccionado por el usuario de cantidad de ventanillas de perecederos
        int SeleccionCantPere = CantVentPerecederos.getSelectedIndex();
        int num2 = 0;
        
        //Ingresa la cantidad de ventanillas seleccionadas de no perecederos
        if(SeleccionCantPere!=0){
            while(SeleccionCantPere!=0){
                String Nombre1 = "Ventana "+ num2;
                Ventanillas Nueva1 = new Ventanillas(Nombre1);
                ListaColaPerecederos.enqueue(Nueva1);
                SeleccionCantPere--;
                num2= num2+1;
                 }
        }
        else{
            
        }
        System.out.println("Ventanillas Perecederos: "+num);
        System.out.println("Ventanillas No Perecederos: "+num2);

        
        
        //Pasa las colas creadas en ventanillas al quiosco
        Quiosco Ventana2 = new Quiosco();
        
        Ventana2.GetVentanillaAUX(ListaColaNoPerecederos, ListaColaPerecederos);
        Ventana2.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_QuioscoBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CantVentNoPerecederos;
    private javax.swing.JComboBox<String> CantVentPerecederos;
    private javax.swing.JLabel NoPerecederosTag;
    private javax.swing.JLabel PerecederosTag;
    private javax.swing.JButton QuioscoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
